#!/usr/bin/env python
"""Derive the tags files of a JHPCE production job from the tagged design-of-record manifest (read-only).

A tags file lists manifest tags, one per line ('#' comments), for scripts/run_stage.py --tags-file. Rows are copied by
tag only (tags unchanged, the manifest is never edited); the header records the manifest SHA-256, the selection, the
rule that allows it and the row counts per task and arm. Order: manifest order (deterministic).

Selection 'fillers_x1_x13' = the GPU rows that docs/PREREG.md section 0 allows before the lambda grid is frozen ("Fits
that depend on no rule (X1 arms none and scvi_adv, X13) may run while A1-A3 are in progress"), restricted to the five
JHPCE tasks of CONSTRAINTS.md SI-39 and to the GPU arms of X13 (scanvi, sysvi). The X13 CPU baselines (harmony,
scanorama, pca) are run by scripts/run_cpu_baselines.py, not by run_stage.py fits. Two jobs (one L40S each, disjoint
tasks, balanced by scripts/cost_model.py lane-hours) plus the union file.

Usage (repo root):
  python cluster/jhpce/make_tags.py --manifest manifests/paper_manifest_stock_pilot_u5_b10.tsv --out-dir cluster/jhpce/tags
  python cluster/jhpce/make_tags.py ... --check     # exit 1 unless the committed files equal a fresh derivation
"""
import argparse
import hashlib
import json
import os
import sys

import pandas as pd

JHPCE_TASKS = ("atac_large", "immune_hum_mou", "lung", "pancreas", "sim2")          # CONSTRAINTS.md SI-39
SELECTIONS = {
    "fillers_x1_x13": dict(
        arms={"X1": ("none", "scvi_adv"), "X13": ("scanvi", "sysvi")},
        rule="docs/PREREG.md sec 0: fits that depend on no rule (X1 arms none and scvi_adv, X13) may run while A1-A3 "
             "are in progress; X13 GPU arms only (CPU baselines run via scripts/run_cpu_baselines.py)",
        jobs={"jobA": ("atac_large", "immune_hum_mou"), "jobB": ("lung", "pancreas", "sim2")},
        expect_rows=250),
}
NO_ADV_INPUT = ("none", "scvi_adv", "scanvi", "sysvi")     # = scripts/run_stage.py NO_ADV_INPUT


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for b in iter(lambda: f.read(1 << 20), b""):
            h.update(b)
    return h.hexdigest()


def placeholders(r):
    """The runner's unfittable() rule (scripts/run_stage.py): numeric lam, adv_input for adversarial arms, integer zstd."""
    out = []
    try:
        float(r["lam"])
    except ValueError:
        out.append(f"lam={r['lam']!r}")
    if r["arm"] not in NO_ADV_INPUT and r["adv_input"] not in ("mean", "sample"):
        out.append(f"adv_input={r['adv_input']!r}")
    if not r["zstd"].lstrip("-").isdigit():
        out.append(f"zstd={r['zstd']!r}")
    return out


def derive(manifest, name):
    spec = SELECTIONS[name]
    M = pd.read_csv(manifest, sep="\t", comment="#", dtype=str, keep_default_na=False)
    if M.tag.duplicated().any():
        raise SystemExit(f"{manifest}: duplicate tags")
    keep = pd.Series(False, index=M.index)
    for ex, arms in spec["arms"].items():
        keep |= (M.experiment == ex) & M.arm.isin(arms)
    sel = M[keep & M.task.isin(JHPCE_TASKS)].copy()
    bad = {r.tag: placeholders(r._asdict()) for r in sel.itertuples() if placeholders(r._asdict())}
    if bad:
        raise SystemExit(f"selected rows hold placeholders (not fittable before the rules): {list(bad.items())[:5]}")
    if len(sel) != spec["expect_rows"]:
        raise SystemExit(f"selection {name} has {len(sel)} rows, expected {spec['expect_rows']}")
    job_tasks = [t for ts in spec["jobs"].values() for t in ts]
    if sorted(job_tasks) != sorted(JHPCE_TASKS):
        raise SystemExit(f"job task lists {spec['jobs']} must partition {JHPCE_TASKS}")
    return M, sel, spec


def render(manifest, msha, name, label, rows, spec, tasks):
    counts = rows.groupby(["task", "arm"]).size()
    lines = ["# tags file for scripts/run_stage.py --tags-file (one manifest tag per line; '#' starts a comment)",
             f"# selection: {name}{'' if label == 'all' else ' ' + label}: "
             + "; ".join(f"{ex} arms {','.join(a)}" for ex, a in spec["arms"].items()) + f"; tasks {' '.join(tasks)}",
             f"# rule: {spec['rule']}; JHPCE tasks per CONSTRAINTS.md SI-39",
             f"# manifest: {manifest} sha256 {msha}",
             f"# rows: {len(rows)}; per task and arm: "
             + "; ".join(f"{t} " + ", ".join(f"{a} {int(n)}" for (tt, a), n in counts.items() if tt == t) for t in tasks),
             f"# generated by: python cluster/jhpce/make_tags.py --manifest {manifest} --out-dir <dir> (manifest order)"]
    return "\n".join(lines + list(rows.tag)) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--manifest", required=True)
    ap.add_argument("--out-dir", required=True)
    ap.add_argument("--selection", default="fillers_x1_x13", choices=sorted(SELECTIONS))
    ap.add_argument("--check", action="store_true", help="compare with the files in --out-dir instead of writing")
    a = ap.parse_args()
    msha = sha256(a.manifest)
    M, sel, spec = derive(a.manifest, a.selection)
    files = {f"{a.selection}.tags": render(a.manifest, msha, a.selection, "all", sel, spec, list(JHPCE_TASKS))}
    for label, tasks in spec["jobs"].items():
        files[f"{a.selection}_{label}.tags"] = render(a.manifest, msha, a.selection, label, sel[sel.task.isin(tasks)],
                                                       spec, list(tasks))
    cnt = sel.groupby(["task", "experiment", "arm", "cond"]).size().rename("rows").reset_index()
    files[f"{a.selection}_counts.csv"] = cnt.to_csv(index=False)
    bad = []
    for fn, text in files.items():
        p = os.path.join(a.out_dir, fn)
        if a.check:
            if not os.path.isfile(p) or open(p).read() != text:
                bad.append(p)
        else:
            os.makedirs(a.out_dir, exist_ok=True)
            with open(p, "w") as f:
                f.write(text)
    summary = dict(manifest=a.manifest, manifest_sha256=msha, selection=a.selection, rows=len(sel),
                   per_job={k: int(sel.task.isin(v).sum()) for k, v in spec["jobs"].items()},
                   tags_sha256={fn: hashlib.sha256(t.encode()).hexdigest() for fn, t in files.items() if fn.endswith(".tags")})
    print(json.dumps(summary, indent=1))
    print(sel.groupby(["task", "arm"]).size().unstack(fill_value=0).to_string())
    if bad:
        print(f"MISMATCH: {bad}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
